### PR TITLE
Feature/setup gitlab pipeline and poetry

### PR DESCRIPTION
**Pull request by ZhukovGreen**
This MR introduces the new setup related to python packaging and CI. What is updated:

- poetry with pyproject.toml
- pre-commit linter in the CI
- new gitlab ci integration (instead of circle ci)
- simplified documentation with simple copy paste startup code

Considerable code changes because of the linting

- [ ] @cr0hn add me (`zhukovgreen`) to the pypi project, so I can push new versions there

closes https://github.com/cr0hn/aiohttp-cache/issues/5

### CODE REVIEW

**Comment by anmv** [comment]
Please merge it!

**Comment by cr0hn** [comment]
I need to review the commit

**Comment by cr0hn** [comment]
oks. I just check the PR. These are things that I'm disagree:

- There's not a good reason to move from circle to gitlab CI.
- There's not a good reason to move README from .rst to .md
- There's not a good reason to move the doc to the README instead of improve the current doc
- I completely disagree to remove setup install way and I don't understand why poetry is now the unique way to install the project.
- I completely disagree to not upload the new versions to Pypi.

The above changes are not technical reasons. I'm sorry but I can't approve this PR for these reasons

**Comment by ZhukovGreen** [comment]
Hi @cr0hn , 

thx for your review.

# poetry 
poetry doesn't apply any restrictions to the way of installing the project. It is fully compatible with pip install. So, from the client's point of view, there is no difference.

# publish to pypi
The pipeline has a deploy stage, where it automatically uploads the newer version to the pypi (https://github.com/cr0hn/aiohttp-cache/blob/feature/setup-gitlab-pipeline-and-poetry/.gitlab-ci.yml#L36)

# docs and the rest
In terms of the documentation, I just think that this is easier for devs to have a short startup code right inside the README. The project is simple and from my POV doesn't required the separate doc URL.
But it is up to you. I can revert this change.

Changes related to gitlab CI and rst->md this is the case of personal preferences, what allows me easier maintanace of the project.

Please reconsider your decision @cr0hn if possible.

**Comment by cr0hn** [comment]
Hi.

Questions. Where I must put my the Pypi credentials, by using gitlab CI?

**Comment by ZhukovGreen** [comment]
> Hi.
> 
> Questions. Where I must put my the Pypi credentials, by using gitlab CI?

Hi @cr0hn , I was assuming that you will add me as a maintainer in pypi project (https://pypi.org/manage/project/aiohttp-cache/collaboration/). In this case, the CI might use my credentials to publish packages as well.

But surely it is also possible to add your pypi credentials to the ci. In this case, you need to:
1. Go https://gitlab.com/zhukovgreen/aiohttp-cache/-/settings/ci_cd (I added you to the repo as maintainer. After accepting the invitation I will make you the owner and become a maintainer).
2. Add env var PYPI_U with the value equal to your pypi login
3. Add env var PYPI_P with the value equal to your pypi password

**Pull request merged**
